services:
  - type: web
    name: php-register-form
    runtime: php
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 -t ."
    envVars:
      - key: DB_HOST
        value: your-db-host
      - key: DB_NAME
        value: your-db-name
      - key: DB_USER
        value: your-db-user
      - key: DB_PASS
        value: your-db-password
